[package]
name = "advent"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
eyre = "0.6.12"
indoc = "2.0.7"
itertools = "0.14.0"
num = "0.4.3"
paste = "1.0"
range-set = "0.1.0"
